name: Build and publish image to Docker hub
on:
    [workflow_dispatch]

jobs:
    publish_images:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: build image
              run: | 
                docker build ./api -t dmitrybaranovsky/devops-qr-code-api:latest
                docker build ./front-ent-nextjs -t dmitrybaranovsky/devops-qr-code-frontend:latest
            - name: push image to docker hub
              run: |
                 docker login -u dmitrybaranovsky -p ${{ secrets.DOCKER_HUB_TOKEN }}
                 docker push dmitrybaranovsky/devops-qr-code-api
                 docker push dmitrybaranovsky/devops-qr-code-frontend:latest
            
